language: php
php:
  - "7.0"

sudo: true

script:
  # Override default Travis script action [phpunit]
  - php -l ./src/*.php
  - sed -i -e "s/__STABLE_TAG__/$TRAVIS_TAG/g" ./src/readme.txt
  - sed -i -e "s/__STABLE_TAG__/$TRAVIS_TAG/g" ./src/${PWD##*/}.php
  - svn co "https://plugins.svn.wordpress.org/$PLUGIN_SLUG" ./svn  --depth immediates
  - cp -R ./src/* ./svn/trunk
  - cp -R ./wp_org/assets/* ./svn/assets

branches:
  only:
    # Enable Travis hook on tags (there is regular expression for semver tag)*
    - "/\\d\\.\\d\\.\\d/"

# Enable Travis deployment
deploy:
  # Use script as a deployment tool
  provider: script
  script: sh ./deploy.sh
  # Restrict deployment only for tags
  on:
    tags: true
